# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x12\x05posts\"D\n\x11\x43reatePostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"P\n\x11UpdatePostRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\"0\n\x11\x44\x65letePostRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"%\n\x12\x44\x65letePostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\x0eGetPostRequest\x12\n\n\x02id\x18\x01 \x01(\t\"C\n\x0fGetPostsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"C\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t2\x9c\x02\n\x0bPostService\x12\x33\n\nCreatePost\x12\x18.posts.CreatePostRequest\x1a\x0b.posts.Post\x12\x33\n\nUpdatePost\x12\x18.posts.UpdatePostRequest\x1a\x0b.posts.Post\x12\x41\n\nDeletePost\x12\x18.posts.DeletePostRequest\x1a\x19.posts.DeletePostResponse\x12-\n\x07GetPost\x12\x15.posts.GetPostRequest\x1a\x0b.posts.Post\x12\x31\n\x08GetPosts\x12\x16.posts.GetPostsRequest\x1a\x0b.posts.Post0\x01\x62\x06proto3')



_CREATEPOSTREQUEST = DESCRIPTOR.message_types_by_name['CreatePostRequest']
_UPDATEPOSTREQUEST = DESCRIPTOR.message_types_by_name['UpdatePostRequest']
_DELETEPOSTREQUEST = DESCRIPTOR.message_types_by_name['DeletePostRequest']
_DELETEPOSTRESPONSE = DESCRIPTOR.message_types_by_name['DeletePostResponse']
_GETPOSTREQUEST = DESCRIPTOR.message_types_by_name['GetPostRequest']
_GETPOSTSREQUEST = DESCRIPTOR.message_types_by_name['GetPostsRequest']
_POST = DESCRIPTOR.message_types_by_name['Post']
CreatePostRequest = _reflection.GeneratedProtocolMessageType('CreatePostRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPOSTREQUEST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.CreatePostRequest)
  })
_sym_db.RegisterMessage(CreatePostRequest)

UpdatePostRequest = _reflection.GeneratedProtocolMessageType('UpdatePostRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPOSTREQUEST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.UpdatePostRequest)
  })
_sym_db.RegisterMessage(UpdatePostRequest)

DeletePostRequest = _reflection.GeneratedProtocolMessageType('DeletePostRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEPOSTREQUEST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.DeletePostRequest)
  })
_sym_db.RegisterMessage(DeletePostRequest)

DeletePostResponse = _reflection.GeneratedProtocolMessageType('DeletePostResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEPOSTRESPONSE,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.DeletePostResponse)
  })
_sym_db.RegisterMessage(DeletePostResponse)

GetPostRequest = _reflection.GeneratedProtocolMessageType('GetPostRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTREQUEST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.GetPostRequest)
  })
_sym_db.RegisterMessage(GetPostRequest)

GetPostsRequest = _reflection.GeneratedProtocolMessageType('GetPostsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTSREQUEST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.GetPostsRequest)
  })
_sym_db.RegisterMessage(GetPostsRequest)

Post = _reflection.GeneratedProtocolMessageType('Post', (_message.Message,), {
  'DESCRIPTOR' : _POST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:posts.Post)
  })
_sym_db.RegisterMessage(Post)

_POSTSERVICE = DESCRIPTOR.services_by_name['PostService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEPOSTREQUEST._serialized_start=22
  _CREATEPOSTREQUEST._serialized_end=90
  _UPDATEPOSTREQUEST._serialized_start=92
  _UPDATEPOSTREQUEST._serialized_end=172
  _DELETEPOSTREQUEST._serialized_start=174
  _DELETEPOSTREQUEST._serialized_end=222
  _DELETEPOSTRESPONSE._serialized_start=224
  _DELETEPOSTRESPONSE._serialized_end=261
  _GETPOSTREQUEST._serialized_start=263
  _GETPOSTREQUEST._serialized_end=291
  _GETPOSTSREQUEST._serialized_start=293
  _GETPOSTSREQUEST._serialized_end=360
  _POST._serialized_start=362
  _POST._serialized_end=429
  _POSTSERVICE._serialized_start=432
  _POSTSERVICE._serialized_end=716
# @@protoc_insertion_point(module_scope)
