# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import posts_pb2 as posts__pb2


class PostServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/posts.PostService/CreatePost',
                request_serializer=posts__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=posts__pb2.Post.FromString,
                )
        self.UpdatePost = channel.unary_unary(
                '/posts.PostService/UpdatePost',
                request_serializer=posts__pb2.UpdatePostRequest.SerializeToString,
                response_deserializer=posts__pb2.Post.FromString,
                )
        self.DeletePost = channel.unary_unary(
                '/posts.PostService/DeletePost',
                request_serializer=posts__pb2.DeletePostRequest.SerializeToString,
                response_deserializer=posts__pb2.DeletePostResponse.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/posts.PostService/GetPost',
                request_serializer=posts__pb2.GetPostRequest.SerializeToString,
                response_deserializer=posts__pb2.Post.FromString,
                )
        self.GetPosts = channel.unary_stream(
                '/posts.PostService/GetPosts',
                request_serializer=posts__pb2.GetPostsRequest.SerializeToString,
                response_deserializer=posts__pb2.Post.FromString,
                )


class PostServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=posts__pb2.CreatePostRequest.FromString,
                    response_serializer=posts__pb2.Post.SerializeToString,
            ),
            'UpdatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePost,
                    request_deserializer=posts__pb2.UpdatePostRequest.FromString,
                    response_serializer=posts__pb2.Post.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=posts__pb2.DeletePostRequest.FromString,
                    response_serializer=posts__pb2.DeletePostResponse.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=posts__pb2.GetPostRequest.FromString,
                    response_serializer=posts__pb2.Post.SerializeToString,
            ),
            'GetPosts': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPosts,
                    request_deserializer=posts__pb2.GetPostsRequest.FromString,
                    response_serializer=posts__pb2.Post.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'posts.PostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PostService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/posts.PostService/CreatePost',
            posts__pb2.CreatePostRequest.SerializeToString,
            posts__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/posts.PostService/UpdatePost',
            posts__pb2.UpdatePostRequest.SerializeToString,
            posts__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/posts.PostService/DeletePost',
            posts__pb2.DeletePostRequest.SerializeToString,
            posts__pb2.DeletePostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/posts.PostService/GetPost',
            posts__pb2.GetPostRequest.SerializeToString,
            posts__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/posts.PostService/GetPosts',
            posts__pb2.GetPostsRequest.SerializeToString,
            posts__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
